---
name: eudi-lib-ios-siop-openid4vp-swift
on:
  - push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          find . -type f \( -name 'Package.swift' -o -name 'Package.resolved' \) -exec sed -i '' "s/https:\/\/github.com\/niscy-eudiw/https:\/\/${{ secrets.USER_NAME }}:${{ secrets.USER_GITHUB_TOKEN }}@github.com\/niscy-eudiw/g" {} \;

          fastlane tests