---
name: build-siop-openid4vp-ios
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run:
          fastlane tests
