---
name: eudi-lib-ios-siop-openid4vp-swift
on:
  - push
jobs:
  build:
    runs-on: "macos-14"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - uses: actions/checkout@v4
      - run:
          fastlane tests

      