---
name: eudi-lib-ios-siop-openid4vp-swift
on:
  - push
jobs:
  build:
    runs-on: "macos-13"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - uses: actions/checkout@v4
      - run: >
          find . -type f \( -name 'Package.swift' -o -name 'Package.resolved' \) -exec sed -i '' "s/https:\/\/github.com\/eu-digital-identity-wallet/https:\/\/${{ secrets.USER_NAME }}:${{ secrets.USER_GITHUB_TOKEN }}@github.com\/eu-digital-identity-wallet/g" {} \;

          fastlane tests

      