---
name: build-siop-openid4vp-ios
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: >
          git config --global --add url."https://${{ secrets.USER_NAME }}:${{
          secrets.USER_GITHUB_TOKEN }}@github".insteadof https://github

          fastlane tests # fastlane just_build