name: build-siop-openid4vp-ios
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run:  echo "fastlane tests coming back soon!" # fastlane tests